"$schema" = "https://schema.tauri.app/config/2"
productName = "openchad"
version = "0.1.0"
identifier = "com.openchad.app"
[build]
frontendDist = "./frontend"
[app]
withGlobalTauri = true
security.capabilities = ["default"]
[[app.windows]]
title = "openchad"
width = 1680
height = 945
decorations = false
maximized = true
[bundle]
icon = [
    "icons/icon.png",
    "icons/icon.ico",
]
